-- Cho biết mức lương trung bình của từng phòng ban

SELECT PHONGBAN.MAPHG, PHONGBAN.TENPHG, AVG(NHANVIEN.LUONG) AS "Lương trung bình"
FROM PHONGBAN
JOIN NHANVIEN ON PHONGBAN.MAPHG = NHANVIEN.PHG
GROUP BY PHONGBAN.MAPHG, PHONGBAN.TENPHG;